producer/producer_nf.go
utils/sflow_test.go

Source and destination mac addresses are fed from `NFV9_FIELD_xx_yyy_MAC`
Closes #15 where the samples were missing either source or destination Mac.
This is supposed to be linked to the sampling direction.

Bugfix NetFlow/IPFIX producer

---

compose/kcg/clickhouse/create.sh

Without it, you will get the error:
```
/entrypoint.sh: sourcing /docker-entrypoint-initdb.d/create.sh
Received exception from server (version 21.5.6):
Code: 82. DB::Exception: Received from localhost:9000. DB::Exception: Database dictionaries already exists.
```

Fix clickhouse startup after restart

---

cmd/enricher/main.go

By setting `-samplingrate=1024` when using the enricher, this will set the value of the field.
Closes #21

Enricher can set sampling rate

---

producer/producer_nf.go

IPFIX supports sending flowEndDeltaMicroseconds (159) and
flowEndDeltaMicroseconds (160) to provide flow timestamps relative to
the exportTime in the IPFIX Message Header.
Use them to calculate flow TimeFlowStart and TimeFlowEnd.
Signed-off-by: Adrian Moreno <amorenoz@redhat.com>

ipfix: support relative flow timestamps

---

decoders/netflow/netflow.go
format/format.go
producer/producer_nf.go
transport/transport.go

Defer unlocking just after taking a lock when possible (when unlock is
done at the very end) and when not trivial (the function body is more
than a couple of lines). This simplifies a bit some functions (no need
to unlock before each return) and for the other, it may avoid a bug in
the future in case a return is inserted into the body of a function.
Use of defer has been optimized a lot in Go and it is believed that
simpler defers have zero overhead since Go 1.14:
https://golang.org/doc/go1.14#runtime
> This release improves the performance of most uses of defer to incur
> almost zero overhead compared to calling the deferred function
> directly. As a result, defer can now be used in performance-critical
> code without overhead concerns.

style: defer unlock when possible/not trivial

---

decoders/netflow/netflow.go
decoders/netflowlegacy/netflow.go
decoders/sflow/sflow.go

The Field type does not match the format on the wire. Decode each
member individually.
Also, a second commit:
The error handling was inconsistent when using `utils.BinaryDecoder`.
All occurrences are now checked an we return early with error and the
incomplete data collected up to now when possible. This can happen
on short packets.

netflow: correctly decode options template set

---

utils/netflow.go
utils/nflegacy.go
utils/sflow.go
utils/stopper.go
utils/stopper_test.go
utils/utils.go
utils/utils_test.go

When Goflow2 is consumed as a Go library, we'd need some tools to allow cancelling the Flow ingestion routines (e.g. to retry a connection).
This PR adds new `Shutdown` methods that interrupt the flow routines, by means of a new `utils.UDPStoppableRoutine` function. The `utils_test.go` and `stopper_test.go` files shows how the mechanism works

Allow Flow Routines to be cancellable

---

transport/kafka/kafka.go

As far as I can tell, this is not used anywhere anymore.

Remove unused KafkaState

---

transport/kafka/kafka.go

Adds more controls for #44:
* `transport.kafka.maxmsgbytes`
* `transport.kafka.flushbytes`
* `transport.kafka.flushfreq`
@shyam334: could you take a look?

Add flags to control Kafka Flush parameters

---

decoders/netflow/netflow.go
decoders/sflow/sflow.go
producer/producer_nf.go
producer/producer_nflegacy.go
producer/producer_sf.go
producer/reflect.go
transport/kafka/kafka.go
utils/netflow.go

Zero-length slice allocations might result in an unnecessary memory allocation if you don't add later data to the slices, which could result in multiple unnecessary allocations per flow received.
This PR suggests to replace constructs like:
```go
templatesFlowSet := make([]netflow.TemplateFlowSet, 0)
```
by:
```go
var templatesFlowSet []netflow.TemplateFlowSet
```
The code is still safe against `nil` references to slice, as Go allows operating with `nil` slices in the `len`, `append` and `range` operators:
If e.g. `templatesFlowSet == nil`:
* `len(templatesFlowSet)` == 0
* `templatesFlowSet = append(templatesFlowSet, XX)` will return a new slice with XX appended.
* `for i, v := range templatesFlowSet` will be a zero-iteration loop.

Avoid unnecessary memory allocations

---

decoders/netflow/netflow.go

There are no mentions of variable length (a [RFC7011/IPFIX feature originally](https://datatracker.ietf.org/doc/html/rfc7011)) in Cisco NetFlow v9 but apparently some implementations (like H3C) send this causing the samples to not be decoded since it's expecting a total sample size of 65kB+.
Seems that Wireshark dissectors do not mind wether it's NetFlow or IPFIX.
https://github.com/wireshark/wireshark/blob/248f11dd1b15bd7322a7fb3e66238eb538c8a9e2/epan/dissectors/packet-netflow.c#L5138
This PR implements the same behavior and removes the check of the version.
Closes #76.

support netflow v9 variable length

---

producer/producer_nf.go

`*1000`  missing to convert basetime from seconds to milliseconds in two cases

In IPFIX DeltaMicroseconds case, basetime must be converted to MS

---

producer/reflect.go

Addresses #89. This change makes the default `mapping.yaml` file parse correctly.

Adding field names to allow ipfix yaml mapping field to parse

---

utils/netflow.go
utils/nflegacy.go
utils/sflow.go

Hello,
I noticed that the transport error are not logged here while they are logged in the enricher example.
This is a small PR to add logging of these errors.

Add logging of transport error

---

utils/utils.go

Flow I'm trying to process will have empty packets sometimes. This results in errors like 
```NetFlow 8 36.263µs Error decoding version: EOF```
Change silently skips empty packets right after they are read.

Silently drop 0 byte packets without processing as flow

---

producer/producer_sf.go

For SrcAS, when there is an AS path, we should keep the value of the dedicated field instead of using the router AS number. For DstAS, if there is no AS path, it is better to keep it to 0 instead of trying to guess it. It may break other workflows that try to be smarter.
See https://github.com/akvorado/akvorado/issues/173.

Fix SrcAS/DstAS for sFlow

---

README.md
cmd/goflow2/main.go

Improve the binding URI with `?count=N` argument.
Example to create 4 sFlow sockets 
```bash
$ ./goflow2 -listen 'sflow://:6343?count=4'
```
Previously, the user would have to do:
```bash
$ ./goflow2 -listen 'sflow://:6343,sflow://:6343,sflow://:6343,sflow://:6343'
```

socket reuse URI argument

---

producer/producer_nf.go

Closes #105 
Certain devices send a single template for both IPv4 and IPv6 traffic.
This checks for length of the address before setting the protobuf field.
In the case where the IP addresses are absent, the `IP_PROTOCOL_VERSION`/`ipVersion` (field: 60) is used to set the Ethernet type.

fix single ip template case

---

docs/protocols.md

In source code:
```go
NFV9_FIELD_SRC_VLAN                     = 58
NFV9_FIELD_DST_VLAN                     = 59
IPFIX_FIELD_vlanId                                = 58
IPFIX_FIELD_postVlanId                            = 59
case netflow.NFV9_FIELD_SRC_VLAN:
DecodeUNumber(v, &(flowMessage.VlanId))
DecodeUNumber(v, &(flowMessage.SrcVlan))
case netflow.NFV9_FIELD_DST_VLAN:
DecodeUNumber(v, &(flowMessage.DstVlan))
```

docs: fix SrcVlan/VlanId mapping between protocols

---

compose/elk/docker-compose.yml
compose/kcg/clickhouse/create.sh
compose/kcg/docker-compose.yml
compose/kcg/grafana/dashboards/viz-ch.json
compose/kcg/grafana/datasources-ch.yml
compose/kcg/prometheus/prometheus.yml

👋 First time caller, long time fan. I was migrating over from GoFlow to GoFlow2 this weekend and ran into a few issues. The first had to do with getting ClickHouse wired up.
This pull request resolves an issue with the mapping between the ClickHouse schema and the `flow.proto` schema that was introduced in #109 (3326554, specifically). In that commit, the casing of the proto fields was updated, but the ClickHouse column names in `create.sh` were not, resulting in the ClickHouse Kafka engine only being able to successfully deserialize fields that without an underscore.

Update Clickhouse schema to match casing of proto

---

cmd/goflow2/mapping.yaml
producer/producer_nf.go
producer/producer_sf.go
producer/reflect.go

Related to https://github.com/netsampler/goflow2/issues/113
Mapping file can specify the following:
```yaml
netflowv9:
mapping:
- field: 34
destination: SamplingRate
endian: little
```
This should support the strange implementation from Mikrotik of the Sampling Rate. This field ends up in the Data frame and not Data Options. Additionally, the records is in little endian.

mapping: support endianness

---

decoders/netflow/netflow.go
decoders/netflow/netflow_test.go
utils/netflow.go

The NetFlow template refactoring caused some issues on software importing the GoFlow2 library (https://github.com/influxdata/telegraf/pull/13104).
This PR tries to reduce the conflicts.

templates: retrofit to avoid issue when upgrading dep

---

cmd/goflow2/main.go
utils/pipe.go

By looking at the first 4 bytes of a packet, GoFlow2 can identify the protocol.
```
NetFlow v5 0x00 0x05
NetFlow v9 0x00 0x09
IPFIX 0x00 0x0A
sFlow v5 0x00 0x00 0x00 0x05
```
Closes #187.

goflow2: allows using a single port for multiple protocols (sFlow, NetFlow, IPFIX)

---

decoders/netflow/netflow.go
producer/proto/producer_nf.go
producer/proto/proto.go

Fixes #206 
The sampling rate was not properly added to IPFIX/NetFlow v9 produced packets.
Two issues were present in the code:
* The actual field in the options was ignored due to a `for` loop consuming all the data.
* The samplingsystem containing the sampling rates of a specific router had a key that listed the port, while some samplers send on a different port the option templates causing the option data being separated from the sample data.

producer: bugfix of sampling mapping for ipfix

---

producer/proto/proto.go

Missing TimeReceivedNs value in netflow v5.
Before and after:

fix: missing time received ns in netflow v5

---

producer/proto/producer_sf.go
producer/proto/producer_test.go

I introduced a bug in #213 and used `0xE000` instead of `0x1FFF`

producer: fix fragment

---

cmd/goflow2/main.go
utils/udp.go

I was testing flows collecting from pmacct and goflow2 and realized that goflow2 is loosing packets (goflow2 should have MORE data, because pmacct is aggregating in memory and flush aggregated)
```sql
SELECT *
FROM collector_compare
Query id: 4d8b440f-06ff-4ff8-b732-8292b5b16b44
┌─type───────┬─pmacct_count────┬─goflow_count────┬─diff───────────┬─percent─┐
│ IPFIX      │ 199.16 thousand │ 190.66 thousand │ -8.50 thousand │ -4.3%   │
│ SFLOW_5    │ 33.23 million   │ 24.47 million   │ -8.75 million  │ -26.3%  │
│ NETFLOW_V5 │ 202.00          │ 203.00          │ 1.00           │ 0.5%    │
└────────────┴─────────────────┴─────────────────┴────────────────┴─────────┘
```
After debugging I realized that when we have `1 socket = 1 worker` -> with high volume of flows per second reading packet …

Add workers, isBlocking and queue size to listen config

---

producer/proto/producer_nf.go

Per https://www.iana.org/assignments/ipfix/ipfix.xhtml
```
Bit 0:    (RS) Reserved.
The value of this bit MUST be 0 until specified
otherwise.
Bit 1:    (DF) 0 = May Fragment,  1 = Don't Fragment.
Corresponds to the value of the DF flag in the
IPv4 header.  Will always be 0 for IPv6 unless
a "don't fragment" feature is introduced to IPv6.
Bit 2:    (MF) 0 = Last Fragment, 1 = More Fragments.
Corresponds to the MF flag in the IPv4 header
or to the M flag in the IPv6 Fragment header,
respectively.  The value is 0 for IPv6 if there
is no fragment header.
Bits 3-7: (DC) Don't Care.
The values of these bits are irrelevant.
0   1   2   3   4   5   6   7
+---+---+---+---+---+---+---+---+
| R | D | M | D | D | D | D | D |
| S | F | F | C | C | C | C | C |
+---+---+---+---+---+---+---+---+
``` …

producer: fix fragment for NetFlow

---

cmd/goflow2/mapping.yaml

Adds an example on how to map sflow packets (and ipfix datagrams containing packet samples) into a new protobuf field.

goflow2: add configuration example for sflow mapping

---

decoders/netflow/netflow.go

When passing a UDP stream of packets, it will now check for the size indicated at the beginning of the packet.
Note: should likely edit Prometheus counters.

decoder: ipfix have max size

---

compose/kcg/grafana/dashboards/viz-ch.json

Addresses #240.
A recent ClickHouse update likely changed the `intDiv` function that is used in the union with numbers. One column was `UInt64`, the other was `Int64` causing an error.

compose: fix kcg dashboard query

---

README.md
docs/performance.md

When getting started using GoFlow2 for the first time, the default settings may not be optimal for every environment.
This extra page hopes to clarify the various configuration in the `listen` arg.

docs: add performance page

---

format/common/text.go

Addresses https://github.com/netsampler/goflow2/issues/245
Custom renderers (`EtypeName`...) were not used due to the name not being a field inside the protobuf.
This fixes by changing the condition and logic.

format: fix renderer on v1

---

producer/proto/messages.go
transport/kafka/kafka.go

* set default partitioner to roundrobin

bug: fix kafka transport default partitioning

---

cmd/goflow2/mapping.yaml
producer/proto/render.go

When using a custom configuration, integers can be represented as a RFC3339 string.

producer: add datetime render

---

decoders/netflow/ipfix.go
decoders/netflow/netflow.go
decoders/netflow/nfv9.go
decoders/netflow/packet.go

If a packet has multiple sets, keep reading, accumulate errors instead of stopping at the first template not found

decoders: do not stop reading sets

---

producer/proto/producer_sf.go

Closes #251
The `etherType` variable was not checked for length and could cause panic.

bugfix: check etype size before decoding

---

producer/proto/producer_nf.go

Formatting a string with version and domain when looking up sampling rate hurts performance. Instead, use a dedicated structure for key. It also reduces the pressure on the GC.
Before:
```
BenchmarkDecodeEncodeNetflow/with_encoding-12             158208              8611 ns/op            8178 B/op        130 allocs/op
BenchmarkDecodeEncodeNetflow/without_encoding-12          162832              7559 ns/op            8178 B/op        130 allocs/op
```
After:
```
BenchmarkDecodeEncodeNetflow/with_encoding-12             138242              8132 ns/op            8176 B/op        129 allocs/op
BenchmarkDecodeEncodeNetflow/without_encoding-12          162312              7306 ns/op            8176 B/op        129 allocs/op
```

producer: increase performance of sampling rate lookup

---

decoders/sflow/datastructure.go
decoders/sflow/packet.go
decoders/utils/types.go
decoders/utils/utils.go

Due to IP and MAC addresses being a non-standard type, utils.BinaryRead was not able to decode them. Move these two types inside utils.go and teach BinaryRead to use them.

decoders: fix sflow parsing of IP and MAC addresses

---

cmd/goflow2/main.go
utils/mute.go
utils/mute_test.go

This adds two CLI arguments that will by default reduce the amount of logs if there is an issue (transport like kafka logs or decoder templates).
Arguments:
* `err.int`: interval to log errors
* `err.cnt`: threshold of errors per interval
If the threshold of errors during an interval is crossed, subsequent errors will be muted until the interval clears.
One of the common case is when Kafka is down:
```
ERRO[0043] transport error                               error="kafka transport kafka: Failed to produce message to topic flow-messages: circuit breaker is open"
WARN[0043] too many transport errors, muting
WARN[0052] skipped 85 transport errors
ERRO[0052] transport error                               error="kafka transport kafka: Failed to produce message to topic flow-messages: circuit …
```

transport: mute errors when too verbose

---

producer/proto/messages.go
producer/proto/messages_test.go
producer/proto/render.go

Add tests for formatting protobuf data that includes unknown fields (custom mapping)
Fix the function to get the bytes from protobuf instead of converting into hex
Add a string renderer to display text sent via samples
Closes #275

feat: add string renderer

---

.github/workflows/docker-release.yml
.github/workflows/docker-release_registry_github.yml
.github/workflows/docker.yml
.github/workflows/docker_registry_github.yml

`latest` tag hasn't been [pushed in a year](https://hub.docker.com/layers/netsampler/goflow2/latest/images/sha256-0276430774c1f5741262098cb426f3ef7147869a5fb65728a02f31c783bafc5c?context=explore). Fixes it.
Closes #286

bug: fix builds to push latest tag

---

metrics/decoder.go

See #288 #287
Preferring here since in the calling function, it also covers v5

bug: fix double count of NetFlow metric

---

utils/udp.go

fix: use sockets count

---

producer/proto/producer_nf.go
producer/proto/producer_test.go

The uptime is in milliseconds and not seconds.
NetFlow v9 producer had a bug and the timestamps were wrong.
Closes #313 and #305

fix: NetFlow v9 bad timestamp calculation

---

package/goflow2.service

send HUP to goflow2 during service reload

add reload option for systemd service

---

producer/proto/render.go

Following #341:
Small optimization: avoids going through the condition first, start with protocol lookup.
Combine the if/else
cc @marioschaefer / @DerInti

fix(renderer): optimize function ProtoName

---

utils/udp.go

A bug in which running:
```
go run cmd/goflow2/main.go -listen sflow://::1:6343/\?count=10
```
would not break

fix: udp receiver not passing errors

---

producer/proto/producer_nf.go
producer/proto/producer_test.go

This was brought by @iqbalaydrus. Cherry-picked the MPLS fixes (the timestamps had been fixed prior).
Closes #284.

fix(producer): mpls labels in NetFlow

---

producer/proto/config_impl.go

Closes #346
Introduced a bug and did not catch the scenario when the configuration is `nil`.

fix(producer): should parse with empty config

---

transport/kafka/kafka.go

Adds TLS configuration for client certificate.
Closes #363

feat(transport): add mTLS for Kafka

---

go.mod
go.sum
utils/utils.go

The project was already (indirectly) using `gopkg.in/yaml.v3`.
So, let’s remove the additional old major version `gopkg.in/yaml.v2` of the same package.

Migrate to `gopkg.in/yaml.v3`

---

Makefile

feat(makefile): use CGO_EXTERNAL to generate a static build

---

compose/kcg/README.md

There is no Zookeper in the Docker Compose anymore, so we can remove it from the README as well.

Remove mention of Zookeeper in kcg example

---

README.md

The `nfl` scheme, initially for NetFlow v5 has been replaced by `netflow` (IPFIX/NetFlow v9/NetFlow v5).
Closes #393.

docs(readme): fix error

---

producer/proto/producer_nf.go
producer/proto/producer_test.go

fix(timestamp): for ipfix, nanoseconds and microseconds are ntp timestamp formats
