netsampler/goflow2

decoders/netflow/netflow.go

Should resolve #1.
Was missing the OptionTemplate Enterprise fields decoding.
Also did few code nits that would have caused issue with `Next()` and variable length.

bugfix: variable length, missing option templates

---

transport/file/transport.go

```bash
$ go run main.go -transport.file=mylog
$ tail -f mylog
$ mv mylog mylog.1
$ kill -1 PID
$ tail -f mylog
```
Closes #3

feature: implement SIGHUP for log rotation

---

.github/workflows/build.yml
.github/workflows/docker-release.yaml
.github/workflows/docker.yaml
.github/workflows/release.yml
Makefile

feature: add arm builds

---

README.md
cmd/enricher/main.go
transport/file/transport.go

* now requires length prefixed messages
* allows custom line separator for text transport output
* fixes #28

bugfix: enricher decoding certain protobuf

---

docs/protocols.md

Same fix as https://github.com/cloudflare/goflow/pull/106

Fix README for SrcPort and DstPort

---

utils/utils.go

In d1e1ace3186d ("Allow Flow Routines to be cancellable (#40)"), the
payload was passed to another goroutine and erased by the next packet
to be received if the goroutine did not process it fast enough. Make
a copy before passing it to the goroutine to fix that.

utils: copy payload before accepting another UDP packet

---

decoders/netflow/netflow.go
utils/netflow.go

* Was improperly decoding scope fields
* Start removing custom errors structures (will optimize template not found)

Bugfix: decoding OptionsTemplateSet

---

format/common/text.go

Map ProtoName for SCTP

---

cmd/enricher/main.go

Bugfix: issues when reading a partial chunk of protobuf from stdin

---

utils/utils.go
utils/utils_test.go

Tentative to use only two channels and use the defer close.
Alternative to #117. Fixes #112 
cc @mariomac @AlexandreYang

Bugfix: fix closing of UDP routine

---

compose/kcg/clickhouse/create.sh
compose/kcg/docker-compose.yml
compose/kcg/grafana/Dockerfile
compose/kcg/grafana/datasources-ch.yml

* Fix bug with ClickHouse SQL configuration loading protobuf
* Add official ClickHouse datasource to Grafana

Compose: updating ClickHouse and Grafana versions

---

decoders/sflow/packet.go
decoders/sflow/sflow.go

allow unknown records for sFlow

---

cmd/goflow2/main.go

Bug found in #152 with a regression introduced in #49. The StateNetFlow was not properly initialized.

app: hotfix

---

producer/producer_sf.go

Fragmentation parsing was not properly supported.
Fixes #184 and #185

producer: fix fragments

---

.github/workflows/docker-release_registry_github.yml

Hoping to find a better way to reuse the tag with `docker buildx`

build: add release container registry workflow

---

docs/protocols.md
producer/proto/render.go

producer: add missing renderer for bgp_next_hop

---

cmd/enricher/main.go

Fixes #211
Enricher's produced message was missing a binary marshaller.
In the future, can try to add a proper JSON formatter.

enricher: add binary marshaller

---

decoders/netflow/netflow.go

Only last Flowset of Netflow packets is currently decoded (in v2), this PR ensure that all Flowsets are decoded

decoder: fix netflow flowsets decoding

---

decoders/netflow/templates.go

A bug fix and optimizations for BasicTemplateSystem. Each commit message has more details about the changes.

Fix and optimize BasicTemplateSystem

---

decoders/netflow/templates.go

Combines #229 and small change.

decoders: improve BasicTemplateSystem

---

decoders/netflow/netflow.go

When passing a UDP stream of packets, it will now check for the size indicated at the beginning of the packet.

decoder: ipfix have max size

---

docs/agents.md

Supersedes https://github.com/netsampler/goflow2/pull/258

docs: add softflowd

---

producer/proto/producer_nf.go

include ObservationDomainId in netflowv9

---

producer/proto/producer_nflegacy.go

Closes https://github.com/netsampler/goflow2/issues/303

fix: uptime/first/last are in millisecond

---

metrics/decoder.go
metrics/producer.go

Additional changes to another PR (closes #298) cc @iqbalaydrus (couldn't send a commit to your branch so had to do it in a new one).

fix: flow_process_nf_delay_seconds metric is not observed (update)

---

producer/proto/render.go

In json format, IP list is now formatted as Hex. This PR will format ip address to the standard notation

IP List renderer

---

.github/workflows/build.yml
.github/workflows/release.yml

Follow-up of https://github.com/netsampler/goflow2/issues/396

ci(release): add armv7
